const languages = [
  { langCode: "hi", langName: "Hindi (हिन्दी)" },
  { langCode: "en", langName: "English" },
  { langCode: "pa", langName: "Punjabi (ਪੰਜਾਬੀ)" },
  { langCode: "as", langName: "Assamese (অসমীয়া)" },
  { langCode: "bn", langName: "Bengali (বাংলা)" },
  { langCode: "gu", langName: "Gujarati (ગુજરાતી)" },
  { langCode: "mr", langName: "Marathi (मराठी)" },
  { langCode: "or", langName: "Odia (ଓଡ଼ିଆ)" },
  { langCode: "si", langName: "Sinhala (සිංහල)" },
  { langCode: "ur", langName: "Urdu (اردو)" },
  { langCode: "ml", langName: "Malayalam (മലയാളം)" },
  { langCode: "ta", langName: "Tamil (தமிழ்)" },
  { langCode: "te", langName: "Telugu (తెలుగు)" },
  { langCode: "ne", langName: "Nepali (नेपाली)" },
  { langCode: "kn", langName: "Kannada (ಕನ್ನಡ)" },
  { langCode: "ar", langName: "Arabic (العربية)" },
  { langCode: "bg", langName: "Bulgarian (български)" },
  { langCode: "hr", langName: "Croatian (hrvatski)" },
  { langCode: "cs", langName: "Czech (čeština)" },
  { langCode: "da", langName: "Danish (dansk)" },
  { langCode: "nl", langName: "Dutch (Nederlands)" },
  { langCode: "et", langName: "Estonian (eesti)" },
  { langCode: "fi", langName: "Finnish (suomi)" },
  { langCode: "fr", langName: "French (Français)" },
  { langCode: "de", langName: "German (Deutsch)" },
  { langCode: "el", langName: "Greek (Ελληνικά)" },
  { langCode: "iw", langName: "Hebrew (עברית)" },
  { langCode: "hu", langName: "Hungarian (magyar)" },
  { langCode: "id", langName: "Indonesian (Indonesia)" },
  { langCode: "it", langName: "Italian (italiano)" },
  { langCode: "ja", langName: "Japanese (日本語)" },
  { langCode: "ko", langName: "Korean (한국어)" },
  { langCode: "lv", langName: "Latvian (latviešu)" },
  { langCode: "lt", langName: "Lithuanian (lietuvių)" },
  { langCode: "no", langName: "Norwegian (norsk)" },
  { langCode: "pl", langName: "Polish (polski)" },
  { langCode: "pt", langName: "Portuguese (português)" },
  { langCode: "ro", langName: "Romanian (română)" },
  { langCode: "ru", langName: "Russian (русский)" },
  { langCode: "sr", langName: "Serbian (српски)" },
  { langCode: "sk", langName: "Slovak (slovenčina)" },
  { langCode: "sl", langName: "Slovenian (slovenščina)" },
  { langCode: "es", langName: "Spanish (español)" },
  { langCode: "sw", langName: "Swahili (swahili)" },
  { langCode: "sv", langName: "Swedish (svenska)" },
  { langCode: "th", langName: "Thai (ไทย)" },
  { langCode: "tr", langName: "Turkish (türkçe)" },
  { langCode: "uk", langName: "Ukrainian (українська)" },
  { langCode: "vi", langName: "Vietnamese (tiếng Việt)" },
  { langCode: "zh", langName: "Chinese (中文)" },
];

export default languages;
